// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXmEXiQjki5vUFYVhKEAgMET9MeCwykAA',
    appId: '1:173191686386:web:82df9e9d818477e2d9486b',
    messagingSenderId: '173191686386',
    projectId: 'moyeser-academey',
    authDomain: 'moyeser-academey.firebaseapp.com',
    storageBucket: 'moyeser-academey.appspot.com',
    measurementId: 'G-37WBVB8L2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx9Xd1MOuANgjKKccQ0th0xvO2Q__aAw8',
    appId: '1:173191686386:android:b45c6422166c6991d9486b',
    messagingSenderId: '173191686386',
    projectId: 'moyeser-academey',
    storageBucket: 'moyeser-academey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAptyIPVayvlZNFXdHK16D65B9jUyx6yUQ',
    appId: '1:173191686386:ios:48059f485fe4db3bd9486b',
    messagingSenderId: '173191686386',
    projectId: 'moyeser-academey',
    storageBucket: 'moyeser-academey.appspot.com',
    iosBundleId: 'com.example.moyeserAcademyWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAptyIPVayvlZNFXdHK16D65B9jUyx6yUQ',
    appId: '1:173191686386:ios:48059f485fe4db3bd9486b',
    messagingSenderId: '173191686386',
    projectId: 'moyeser-academey',
    storageBucket: 'moyeser-academey.appspot.com',
    iosBundleId: 'com.example.moyeserAcademyWeb',
  );
}
